// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKmSPjb2QpHO1HmfbajltVaL20meyFalM',
    appId: '1:444376303939:web:759492a9d35a660515c7f6',
    messagingSenderId: '444376303939',
    projectId: 'jobapp-68dae',
    authDomain: 'jobapp-68dae.firebaseapp.com',
    storageBucket: 'jobapp-68dae.firebasestorage.app',
    measurementId: 'G-Y9VHZVZ59R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-dJ035f3olDQ-413FwDX1Y4jChJvzaHI',
    appId: '1:444376303939:android:019fb2eb5e5fcdd915c7f6',
    messagingSenderId: '444376303939',
    projectId: 'jobapp-68dae',
    storageBucket: 'jobapp-68dae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1KIqL4t8_BGmPZo6xcmsg8gDaOMNJ4OQ',
    appId: '1:444376303939:ios:126df4ca09ce3a5815c7f6',
    messagingSenderId: '444376303939',
    projectId: 'jobapp-68dae',
    storageBucket: 'jobapp-68dae.firebasestorage.app',
    iosBundleId: 'com.example.job360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1KIqL4t8_BGmPZo6xcmsg8gDaOMNJ4OQ',
    appId: '1:444376303939:ios:126df4ca09ce3a5815c7f6',
    messagingSenderId: '444376303939',
    projectId: 'jobapp-68dae',
    storageBucket: 'jobapp-68dae.firebasestorage.app',
    iosBundleId: 'com.example.job360',
  );
}
